### ISSUE TITLE
Documentation and wiki

### ISSUE THREAD

**Issue by madb1lly** [fabricedesre/servonk#11]
Hi Fabrice,

It's not possible to do pull requests on a GitHub wiki so how would you like us to contribute to documentation? Create a wiki folder within the code and manually create markdown files? Html?

What about explanation of how Servonk works? Control flow, architecture etc? Will this be in the code comments? Should it be in the wiki? Do you eventually foresee automated documentation?

Cheers

**Comment by fabricedesre** [comment]
I think we can just use the github wiki for things like build steps with details for each distribution.
And yes, I should write down at least a high level overview of how the whole thing is put together... Automated documentation can be done both on the Rust and JS side but I don't think we have enough comments yet.

**Comment by madb1lly** [comment]
Currently there's no wiki for your repo. I can create a wiki in my fork but there's no way to do pull requests on wikis, or keep them in sync otherwise, as far as I can tell - it all has to be done manually.

That's why I suggested a "manual" wiki as an alternative, a folder in your repo which people can fork and then update the docs and do pull requests.

Or, you make a separate repo just for the servonk wiki, and give permission for people to edit it directly. This overcomes the problem of not being able to do pull requests on the wiki pages.

I also looked into github "organisations" to see if they can have top-level wikis covering many repos, but this isn't possible.

**Comment by fabricedesre** [comment]
Here it is: https://github.com/fabricedesre/servonk/wiki/Servonk

**Comment by madb1lly** [comment]
Thanks. So if we want to contribute to the wiki, the easiest way is probably:
- Fork your Servonk repo
- Edit our fork of the Servonk wiki
- Tell you we've made some changes to consider including in your wiki

**Comment by fabricedesre** [comment]
Hm, I hoped I could grant edit rights to people I trust directly in this repo...

**Comment by fabricedesre** [comment]
Thanks! I will close this one since you convinced me that a doc folder is better than the wiki.
