### ISSUE TITLE
Suggest Reddit group

### ISSUE THREAD

**Issue by vandys** [fabricedesre/servonk#26]
This is a really, really exciting concept.  It very much opens the door for some of the design changes
identified in Ben Francis' paper on Firefox OS's history.  Being relatively karma-less, I can't create
/r/Servonk, but it seems like it would be a useful place to communicate?

**Comment by madb1lly** [comment]
Hi @vandys! Fabrice can decide, but with the community being quite small at present I think that it would be better to stick to existing channels. There's already https://www.reddit.com/r/FireFoxOS/ which is full of people who are interested in the subject... The level of discussion the may not directly correlate to interest in Servonk but it got you an idea of how much discussion is going on.

The place with most discussion is telegram: https://huit.re/ServonkTelegram

**Comment by vandys** [comment]
Thanks.  I wrote up some details and put'em on the subreddit, so will see how it goes.
