### ISSUE TITLE
Simple Web OS based on Servo, WebAssembly and Redox

### ISSUE THREAD

**Issue by eshikafe** [fabricedesre/servonk#27]
I have been thinking of a very simple OS that runs a Servo process for each desktop element (GUI, file system manager, terminal, Office app etc) optimized with WebAssembly for both mobile and desktop. With a very simple microkernel like Redox.

Does this make sense? Is this also feasible?

**Comment by vandys** [comment]
This is really the wrong place to be blue sky-ing an OS architecture based on WWW standards.  Have you looked at the reddit group for Firefox OS?

**Comment by eshikafe** [comment]
Thanks for the hint.
